basePath: /api/auth
definitions:
  handler.LoginRequest:
    properties:
      msisdn:
        type: string
      password:
        type: string
    required:
    - msisdn
    - password
    type: object
  model.User:
    properties:
      id:
        type: string
      msisdn:
        type: string
      name:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  utils.ErrorResponse:
    properties:
      details: {}
      message:
        example: Error
        type: string
    type: object
  utils.SuccessResponse:
    properties:
      data: {}
      message:
        example: Success
        type: string
    type: object
host: localhost:8001
info:
  contact:
    email: support@example.com
    name: API Support
  description: This is a service for user authentication.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Auth Service API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate user with MSISDN and password
      parameters:
      - description: Login Request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Login user
      tags:
      - auth
  /me:
    get:
      description: Get information about the logged in user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get current user profile
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Register with MSISDN and username
      parameters:
      - description: Register Request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Register new user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
